// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtiRCuhlfHOYg2FQ81XA_6vcxCEMUD52g',
    appId: '1:217006222986:web:e069d68d5b63e486b84773',
    messagingSenderId: '217006222986',
    projectId: 'flutterproject-da597',
    authDomain: 'flutterproject-da597.firebaseapp.com',
    storageBucket: 'flutterproject-da597.appspot.com',
    measurementId: 'G-06P60X8RC3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgPAaOmNMA-6kw5Q0xv7hf4R2SBDaPKog',
    appId: '1:217006222986:android:1d4af7261e90eb40b84773',
    messagingSenderId: '217006222986',
    projectId: 'flutterproject-da597',
    storageBucket: 'flutterproject-da597.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqanH3WGU3j8uqFbdejLGi8zO1NrAEY7Q',
    appId: '1:217006222986:ios:400390ba91d05b3eb84773',
    messagingSenderId: '217006222986',
    projectId: 'flutterproject-da597',
    storageBucket: 'flutterproject-da597.appspot.com',
    iosClientId: '217006222986-fvf9nucalplj5ippui29qcb6qnspqjl2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProject2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqanH3WGU3j8uqFbdejLGi8zO1NrAEY7Q',
    appId: '1:217006222986:ios:400390ba91d05b3eb84773',
    messagingSenderId: '217006222986',
    projectId: 'flutterproject-da597',
    storageBucket: 'flutterproject-da597.appspot.com',
    iosClientId: '217006222986-fvf9nucalplj5ippui29qcb6qnspqjl2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProject2',
  );
}
